export const PRODUCT_VIEW_CONSTANTS = {
  PAGE_SIZE: 8,
  INITIAL_TOPBAR_OFFSET_PX: 63,
  INITIAL_TOOLBAR_HEIGHT_PX: 62,
  TOPBAR_OVERLAP_PX: 3,
  FILTER_BAR_OFFSET_PX: 1,
  LOAD_MORE_ROOT_MARGIN: '0px 0px 160px 0px',
  LOAD_MORE_THRESHOLD: 0.05,
} as const;
